[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library_types = { path = "../library_types" }
db_wrapper = { path = "../db_wrapper" }
file_io = { path = "../file_io"}
tokio = { version = "1.27.0", features = ["full"] }
async-recursion = "1.0.4"
lazy_static = "1.4.0"
log = "0.4.14"
rust-code-analysis = "0.0.25"
rust-code-analysis-cli = "0.0.25"
uuid = "1.4.0"
rbook = "0.5.0"

cxx = "1.0.83"

[build-dependencies]
cxx-build = "1.0.83"

