[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library_types = { path = "../library_types" }
db_wrapper = { path = "../db_wrapper" }
async-recursion = "1.0.4"
lazy_static = "1.4.0"
log = "0.4.20"
rbook = "0.5.0"
image = "0.24.6"
pdf = "0.8.1"
iter_tools = "0.1.4"
uuid = "1.4.1"
cxx = "1.0.83"

[build-dependencies]
cxx-build = "1.0.83"

